config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :customers, controllers: { registrations: 'customers/registrations', 
                                        sessions: 'customers/sessions',
                                        passwords: 'customers/passwords', 
                                        omniauth_callbacks: "customers/omniauth_callbacks" }
  devise_scope :customer do
    get '/settings', to: 'customers#settings'
    put '/change_password', to: 'customers#change_password'
    put '/change_personal_info', to: 'customers#change_personal_info'
  end
  
  resources :orders, only: [:index, :show, :new, :update, :destroy] do
    put "/add_to_order", to: "orders#add_to_order", on: :collection 
    get '/checkout_address', to: 'orders#checkout_address', on: :collection 
    post '/set_address', to: 'orders#set_address', on: :collection 
    get '/checkout_delivery', to: 'orders#checkout_delivery', on: :collection 
    put '/set_delivery', to: 'orders#set_delivery', on: :collection 
    get '/checkout_payment', to: 'orders#checkout_payment', on: :collection 
    get '/checkout_confirm', to: 'orders#checkout_confirm', on: :collection 
    get '/checkout_complete', to: 'orders#checkout_complete', on: :collection 
  end 
  
  resources :order_items, only: [:destroy] 
  resources :credit_cards, only: [:create, :update] 
  resources :addresses, only: [:update, :create]  
  resources :books, only: [:show, :index] do 
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:show]
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
         
  has_many :orders
  has_many :ratings, dependent: :destroy
  has_one :credit_card

  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"

  validates_presence_of :email, :encrypted_password, :firstname, :lastname
  #validates :email, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def create_new_order
    self.orders.create
  end

  def current_order
    self.orders.in_progress.last
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.first_name   
      user.lastname = auth.info.last_name
    end
  end

  def title 
    self.firstname + " " + self.lastname
  end 
end

app/controllers/customers/confirmations_controller.rb
class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = Customer.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_customer_registration_url
    end
  end
end

app/controllers/customers/passwords_controller.rb
class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  #def update
#
  #end

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:customer).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:customer).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/customers/unlocks_controller.rb
class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :fetch_data_for_settings_page

  def settings 
  end

  def change_personal_info
    current_customer.update(name_email_params)
    if current_customer.save
      flash[:success] = "Your data was successfully updated."
      redirect_to settings_path
    else
      flash.now[:error] = "You've got some errors. Check it below."
      render "settings"
    end
  end

  def change_password
    if old_and_new_pass_ok?
      update_password
    elsif !old_pass_valid?
      redirect_to_settings_with_error("You entered wrong current password. Pls try again.")
    else 
      redirect_to_settings_with_error("New password should have at least 8 characters. Pls try again.")
    end
  end    

  private

  def update_password
    @customer = current_customer
    @customer.update(password: password_params[:new_password])
    sign_in @customer, :bypass => true
    flash[:success] = "Your password successfully changed."
    redirect_to settings_path
  end

  def redirect_to_settings_with_error(error_massage)
    flash[:error] = error_massage
    redirect_to settings_path
  end

  def password_params 
    params.require(:customer).permit(:old_password, :new_password)
  end

  def old_and_new_pass_ok?
    old_pass_valid? && password_params[:new_password].size >= 8
  end

  def old_pass_valid?
    current_customer.valid_password?(password_params[:old_password]) 
  end

  def name_email_params
    params.require(:customer).permit(:email, :lastname, :firstname)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/settings.html.haml
.container
  %h1 Settings
  .row
    .col-md-6
      %h2.underlined-h2.add-margin-bot Billing address
      .row
        .col-md-8
          = form_for @billing_address, html: {class: "billing-address-form"} do |f|
            -if @billing_address.errors.any?
              %div.alert.alert-danger
                - @billing_address.errors.full_messages.each do |msg|
                  %div= "- " + msg
            .form-group
              = f.label :firstname, "First name", class: "control-label"
              = f.text_field :firstname, class: "form-control"
            .form-group
              = f.label :lastname, "Last name", class: "control-label"
              = f.text_field :lastname, class: "form-control"
            .form-group
              = f.label :address, "Sreet address", class: "control-label"
              = f.text_field :address, class: "form-control"
            .form-group
              = f.label :city, "City", class: "control-label"
              = f.text_field :city, class: "form-control"
            .form-group
              = f.label :country_id, "Country", class: "control-label"
              = f.collection_select :country_id, @countries.order('name ASC'), :id, :name, {}, {class: "form-control"}
            .form-group
              = f.label :zipcode, "Zip", class: "control-label"
              = f.text_field :zipcode, class: "form-control"
            .form-group
              = f.label :phone, "Phone", class: "control-label"
              = f.text_field :phone, class: "form-control"
            =hidden_field_tag 'address_type', 'billing' 
            .form-group
              = f.submit "Save", class: "btn btn-primary"

    .col-md-6
      %h2.underlined-h2 Shipping address
      .row
        .col-md-8
          = form_for @shipping_address, html: {class: "shipping-address-form"} do |f|
            .form-group
              = check_box_tag :use_billing_as_shipping, "1", current_customer.billing_address == current_customer.shipping_address && @shipping_address.errors.empty?, class: "checkbox-use-bill-address"
              = label_tag :use_billing_as_shipping, "Use billing address"
            -if @shipping_address.errors.any?
              %div.alert.alert-danger
                - @shipping_address.errors.full_messages.each do |msg|
                  %div= "- " + msg 
            .ship-address-form-fields
              .form-group
                = f.label :firstname, "First name", class: "control-label"
                = f.text_field :firstname, class: "form-control"
              .form-group
                = f.label :lastname, "Last name", class: "control-label"
                = f.text_field :lastname, class: "form-control"
              .form-group
                = f.label :address, "Sreet address", class: "control-label"
                = f.text_field :address, class: "form-control"
              .form-group
                = f.label :city, "City", class: "control-label"
                = f.text_field :city, class: "form-control"
              .form-group
                = f.label :country_id, "Country", class: "control-label"
                = f.collection_select :country_id, @countries.order('name ASC'), :id, :name, {}, {class: "form-control"}
              .form-group
                = f.label :zipcode, "Zip", class: "control-label"
                = f.text_field :zipcode, class: "form-control"
              .form-group
                = f.label :phone, "Phone", class: "control-label"
                = f.text_field :phone, class: "form-control"
              =hidden_field_tag 'address_type', 'shipping' 
              -if current_customer.billing_address == current_customer.shipping_address
                .form-group
                  = f.submit "Save", class: "btn btn-primary"
            -unless current_customer.billing_address == current_customer.shipping_address
              .form-group
                = f.submit "Save", class: "btn btn-primary"

  .row
    .col-md-6
      %h2.underlined-h2 Name and email
      .row
        .col-md-8
          = form_for current_customer, url: change_personal_info_path, html: {class: "personal-info-form"}, method: :put do |f|
            -if current_customer.errors.any?
              %div.alert.alert-danger
                - current_customer.errors.full_messages.each do |msg|
                  %div= "- " + msg
            .form-group
              = f.label :firstname, "First name", class: "control-label"
              = f.text_field :firstname, class: "form-control"
            .form-group
              = f.label :lastname, "Last name", class: "control-label"
              = f.text_field :lastname, class: "form-control"
            .form-group
              = f.label :email, "Email", class: "control-label"
              = f.email_field :email, class: "form-control"
            .form-group
              = f.submit "Save", class: "btn btn-primary"

    .col-md-6
      %h2.underlined-h2 Password
      .row
        .col-md-8
          = form_for current_customer, url: change_password_path, html: {class: "password-form"}, method: :put do |f|
            .form-group
              = f.label :old_password, "Old password", class: "control-label"
              = f.password_field :old_password, autocomplete: "off", class: "form-control"
            .form-group
              = f.label :new_password, "New password", class: "control-label"
              = f.password_field :new_password, autocomplete: "off", class: "form-control" 
              %em 8 characters minimum
            .form-group
              = f.submit "Change password", class: "btn btn-primary"

  .row
    .col-md-12
      %h2.underlined-h2 Remove account
      = link_to "Please remove my account", registration_path(current_customer), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-primary"
      %em (all your data will be lost)