config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :customers, controllers: { registrations: 'customers/registrations', 
                                        sessions: 'customers/sessions',
                                        passwords: 'customers/passwords', 
                                        omniauth_callbacks: "customers/omniauth_callbacks" }
  devise_scope :customer do
    get '/settings', to: 'customers#settings'
    put '/change_password', to: 'customers#change_password'
    put '/change_personal_info', to: 'customers#change_personal_info'
  end
  
  resources :orders, only: [:index, :show, :new, :update, :destroy] do
    put "/add_to_order", to: "orders#add_to_order", on: :collection 
    get '/checkout_address', to: 'orders#checkout_address', on: :collection 
    post '/set_address', to: 'orders#set_address', on: :collection 
    get '/checkout_delivery', to: 'orders#checkout_delivery', on: :collection 
    put '/set_delivery', to: 'orders#set_delivery', on: :collection 
    get '/checkout_payment', to: 'orders#checkout_payment', on: :collection 
    get '/checkout_confirm', to: 'orders#checkout_confirm', on: :collection 
    get '/checkout_complete', to: 'orders#checkout_complete', on: :collection 
  end 
  
  resources :order_items, only: [:destroy] 
  resources :credit_cards, only: [:create, :update] 
  resources :addresses, only: [:update, :create]  
  resources :books, only: [:show, :index] do 
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:show]
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :book
  belongs_to :customer

  validates_presence_of :rating_number, :review, :book, :customer

  scope :approved, -> {where(approved: true)}
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :find_book, only: [:new, :create]
  before_action :authenticate_customer!
  
  def new
    @rating = Rating.new
  end

  def create 
    @rating = current_customer.ratings.build(rating_params)
    if @rating.save
      redirect_to @book, notice: "Thank you for review! It will appear on this page after moderation."
    else    
      render 'new'
    end
  end

  private
  def rating_params
    params.require(:rating).permit(:review, :rating_number, :book_id)
  end

  def find_book
   @book = Book.find(params[:book_id])
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/new.html.haml
.container
  %h1 
    New review for
    =link_to @book.title, @book

  - if @rating.errors.any?
    %div.alert.alert-danger
      %strong Review can't be save because: 
      - @rating.errors.full_messages.each do |msg|
        %div= "- " + msg

  =form_for @rating, url: book_ratings_path(@book) do |f|
    .form-group 
      =f.label :rating_number, "Rating:", class: "control-label"
      %span.star-rating
        -(1..5).each do |i|
          =f.radio_button :rating_number, i
          %i
    .form-group 
      =f.label :review, "Text:", class: "control-label"
      =f.text_area :review, class: "form-control"
      =f.hidden_field :book_id, :value => @book.id
    .form-group
      =f.submit 'Add review', class: "btn btn-primary"
      %span
        or
        =link_to "Cencel", @book 