config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :customers, controllers: { registrations: 'customers/registrations', 
                                        sessions: 'customers/sessions',
                                        passwords: 'customers/passwords', 
                                        omniauth_callbacks: "customers/omniauth_callbacks" }
  devise_scope :customer do
    get '/settings', to: 'customers#settings'
    put '/change_password', to: 'customers#change_password'
    put '/change_personal_info', to: 'customers#change_personal_info'
  end
  
  resources :orders, only: [:index, :show, :new, :update, :destroy] do
    put "/add_to_order", to: "orders#add_to_order", on: :collection 
    get '/checkout_address', to: 'orders#checkout_address', on: :collection 
    post '/set_address', to: 'orders#set_address', on: :collection 
    get '/checkout_delivery', to: 'orders#checkout_delivery', on: :collection 
    put '/set_delivery', to: 'orders#set_delivery', on: :collection 
    get '/checkout_payment', to: 'orders#checkout_payment', on: :collection 
    get '/checkout_confirm', to: 'orders#checkout_confirm', on: :collection 
    get '/checkout_complete', to: 'orders#checkout_complete', on: :collection 
  end 
  
  resources :order_items, only: [:destroy] 
  resources :credit_cards, only: [:create, :update] 
  resources :addresses, only: [:update, :create]  
  resources :books, only: [:show, :index] do 
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:show]
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  
  POSSIBLE_STATES = ['in_progress', 'completed', 'in_delivery', 'delivered', 'canceled']
  aasm column: "state" do
    state POSSIBLE_STATES[0].to_sym, initial: true
    state POSSIBLE_STATES[1].to_sym, after_enter: :set_completed_date
    state POSSIBLE_STATES[2].to_sym
    state POSSIBLE_STATES[3].to_sym
    state POSSIBLE_STATES[4].to_sym

    event :complete do
      transitions from: POSSIBLE_STATES[0].to_sym, to: POSSIBLE_STATES[1].to_sym
    end
  end

  default_scope { order('id DESC') } 

  belongs_to :customer
  belongs_to :credit_card
  belongs_to :delivery_type
  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"
  
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items

  validates_presence_of :completed_date, if: -> {self.state == POSSIBLE_STATES[1]}
  validates :state, inclusion: { in: POSSIBLE_STATES }, presence: true

  def add_to_order(book, quantity=1)  
    if order_item = self.order_items.find_by(book: book)
      order_item.quantity += quantity.to_i
      order_item.save
    else 
      self.order_items.create(price: book.price, quantity: quantity, book: book)
    end
    self.calc_and_set_total_price
  end

  def remove_from_order(item_id)
    OrderItem.find(item_id).destroy if self.order_items.ids.include?(item_id.to_i)
    self.destroy if self.order_items.empty?
  end

  def calc_and_set_total_price
    if self.order_items.any?
      item_total = self.order_items.inject(0) {|sum, i| sum + i.price*i.quantity} 
      shipping_price = self.delivery_type ? self.delivery_type.price : 0 
      self.total_price = item_total + shipping_price
    else 
      self.total_price = 0
    end
    self.save
  end

  def items_qty
    self.order_items.inject(0) {|sum, i| sum + i.quantity} if self.order_items.any?
  end

  def state_enum
    POSSIBLE_STATES
  end

  def set_completed_date
    self.update(completed_date: Date.today)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_current_order, only: [:checkout_address, :checkout_delivery, :checkout_payment, :checkout_confirm, :checkout_complete]
  before_action :fetch_countries, only: [:checkout_address, :set_address]
  before_action :authenticate_customer!, only: [:index]

  def new #cart   
  end
  
  def index #customer's orders list
  end

  def show #one order
    @order = Order.find(params[:id])
    authorize! :read, @order
  end

  def update #update cart
    @current_order.order_items.each_with_index do |item, index| 
      item.update(quantity: params["item-#{index}"])
    end
    @current_order.calc_and_set_total_price
    redirect_to action: "new"
  end

  def destroy #empty cart
    @current_order.destroy
    session[:current_order_id] = nil
    redirect_to books_path, notice: "Cart is empty now."
  end

  def add_to_order
    if @current_order 
      @current_order 
    else
      @current_order = Order.create
      session[:current_order_id] = @current_order.id
    end
    @book = Book.find(order_params[:book_id])
    @current_order.add_to_order(@book, order_params[:quantity])
    redirect_to action: "new"
  end 

#CHECKOUT WIZARD:
  #step 1
  def checkout_address
    assign_checkout_address_form
  end 

  def set_address
    @checkout_address_form = CheckoutAddressForm.new(checkout_address_form_params)
    if @checkout_address_form.save(@current_order, current_customer)
      redirect_to action: "checkout_delivery"
    else
      render "checkout_address"
    end
  end 

  #step 2
  def checkout_delivery
    @delivery_types = DeliveryType.all
  end 

  def set_delivery
    if @current_order.update(delivery_type_id: params[:delivery_type])
      @current_order.calc_and_set_total_price
      redirect_to action: "checkout_payment"
    else
      @delivery_types = DeliveryType.all
      render "checkout_delivery"
    end
  end 

  #step 3
  def checkout_payment
    @credit_card = if current_order.credit_card
      current_order.credit_card
    elsif current_customer
      CreditCard.new(firstname: current_customer.firstname, lastname: current_customer.lastname)
    else
      CreditCard.new
    end
  end 
  #(form on this step sends data to CreditCards controller)

  #step 4
  def checkout_confirm
  end 

  #step 5
  def checkout_complete
    @current_order.complete
    @order = @current_order
    session[:current_order_id] = nil
    render "show"
  end 


  private 
  def order_params
    params.permit(:quantity, :book_id)
  end

  def checkout_address_form_params
    params.require(:checkout_address_form).permit(:b_firstname, 
                                                  :b_lastname, 
                                                  :b_address, 
                                                  :b_city, 
                                                  :b_country_id, 
                                                  :b_zipcode, 
                                                  :b_phone, 
                                                  :s_firstname, 
                                                  :s_lastname, 
                                                  :s_address, 
                                                  :s_city, 
                                                  :s_country_id, 
                                                  :s_zipcode, 
                                                  :s_phone,
                                                  :use_billing_as_shipping)
  end

  def assign_checkout_address_form
    @checkout_address_form = CheckoutAddressForm.new
    unless fetch_addresses_from(@current_order)
      fetch_addresses_from(current_customer) if current_customer
    end
  end

  def fetch_addresses_from(order_or_customer)
    if order_or_customer.shipping_address
      @ba = order_or_customer.billing_address if order_or_customer.billing_address
      @sa = order_or_customer.shipping_address unless order_or_customer.billing_address == order_or_customer.shipping_address
      assign_bill_address_fields(@checkout_address_form, @ba) if @ba
      assign_ship_address_fields(@checkout_address_form, @sa) if @sa
      true
    else 
      false
    end
  end

  def assign_bill_address_fields(form, ba)
    form.b_firstname = ba.firstname
    form.b_lastname = ba.lastname 
    form.b_address = ba.address 
    form.b_city = ba.city
    form.b_country_id = ba.country_id
    form.b_zipcode = ba.zipcode
    form.b_phone = ba.phone
  end 

  def assign_ship_address_fields(form, sa)
    form.s_firstname = sa.firstname
    form.s_lastname = sa.lastname 
    form.s_address = sa.address 
    form.s_city = sa.city
    form.s_country_id = sa.country_id
    form.s_zipcode = sa.zipcode
    form.s_phone = sa.phone
    form.use_billing_as_shipping = false
  end 

  def check_current_order
    redirect_to action: "new" unless @current_order
  end 

  def fetch_countries 
    @countries = Country.all
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_checkout_nav.html.haml
.row
  .col-md-3
    %h1.checkout-h1 Checkout
  .col-md-9.checkout-nav
    .checkout-nav-lnk-wrap{class: "#{'active' if (controller.controller_name == 'orders' && controller.action_name == 'set_address') || current_page?(checkout_address_orders_path)}  #{"done" if @current_order.billing_address}"}
      =link_to checkout_address_orders_path do  
        .text-lnk Address
        .progress-line
          .step-cercle
            %span.step-number 1
            %span.step-done-icon{class: 'glyphicon glyphicon glyphicon-ok'}
    .checkout-nav-lnk-wrap{class: "#{'active' if (controller.controller_name == 'orders' && controller.action_name == 'set_delivery') || current_page?(checkout_delivery_orders_path)} #{"done" if @current_order.delivery_type}"}
      =link_to checkout_delivery_orders_path do 
        .text-lnk Delivery
        .progress-line
          .step-cercle
            %span.step-number 2
            %span.step-done-icon{class: 'glyphicon glyphicon glyphicon-ok'}
    .checkout-nav-lnk-wrap{class: "#{'active' if (controller.controller_name == 'credit_cards' && (controller.action_name == 'create' || controller.action_name == 'update')) || current_page?(checkout_payment_orders_path)} #{"done" if @current_order.credit_card}"}
      =link_to checkout_payment_orders_path do 
        .text-lnk Payment
        .progress-line
          .step-cercle
            %span.step-number 3
            %span.step-done-icon{class: 'glyphicon glyphicon glyphicon-ok'}
    .checkout-nav-lnk-wrap{class: "#{cp(checkout_confirm_orders_path)}"}
      =link_to checkout_confirm_orders_path do 
        .text-lnk Confirm
        .progress-line
          .step-cercle
            %span.step-number 4
            %span.step-done-icon{class: 'glyphicon glyphicon glyphicon-ok'}    }

app/views/orders/_order_details.html.haml
.row
  .col-md-3
    %h3 
      Shipping address
      -if current_page?(checkout_confirm_orders_path)  
        %small= link_to "(edit)", checkout_address_orders_path
    %div= "#{order.shipping_address.firstname} #{order.shipping_address.lastname}"
    %div= order.shipping_address.address
    %div= "#{order.shipping_address.city} #{order.shipping_address.zipcode}"
    %div= order.shipping_address.country.name
    %div= "Phone: #{order.shipping_address.phone}"
  .col-md-3
    %h3 
      Billing address 
      -if current_page?(checkout_confirm_orders_path) 
        %small= link_to "(edit)", checkout_address_orders_path
    %div= "#{order.billing_address.firstname} #{order.billing_address.lastname}"
    %div= order.billing_address.address
    %div= "#{order.billing_address.city} #{order.billing_address.zipcode}"
    %div= order.billing_address.country.name
    %div= "Phone: #{order.billing_address.phone}"
  .col-md-3
    %h3 
      Shipments 
      -if current_page?(checkout_confirm_orders_path) 
        %small= link_to "(edit)", checkout_delivery_orders_path
    %div= "#{order.delivery_type.title} (#{number_to_currency(order.delivery_type.price)})"
  .col-md-3
    %h3 
      Payment information 
      -if current_page?(checkout_confirm_orders_path)
        %small= link_to "(edit)", checkout_payment_orders_path
    %div= "**** **** **** #{order.credit_card.number.split("").last(4).join("")}"
    %div= "#{order.credit_card.exp_month}/20#{order.credit_card.exp_year}"
.row.cart
  .col-md-12
    %br/ 
    %h3 
      Order items
      -if current_page?(checkout_confirm_orders_path) 
        %small= link_to "(edit)", new_order_path
  =render partial: "order_items_list", locals: {order: order}
    

app/views/orders/_order_items_list.html.haml
.col-md-12
  %table{class: "table"}
    %thead
      %tr
        %td BOOK
        %td PRICE
        %td QTY
        %td TOTAL
    %tbody
      -order.order_items.each_with_index do |item, index|
        %tr
          %td
            = link_to item.book do
              = image_tag item.book.image.thumb_small.url.to_s 
              = item.book.title
          %td= number_to_currency(item.book.price)
          -if current_page?(new_order_path) 
            %td= number_field_tag "item-#{index}", item.quantity, within: 1..100, class: 'quantity-input'
          -else
            %td= item.quantity
          %td= number_to_currency(item.book.price * item.quantity)
          -if current_page?(new_order_path) 
            %td{class: "remove_link"}
              = link_to item, method: :delete do 
                %span{"aria-hidden" => "true"} &times;
.col-md-6.col-md-offset-6.clearfix.order-summary-block
  -@shipping_price = order.delivery_type ? order.delivery_type.price : 0
  .order-summary-line
    SUBTOTAL: 
    %span=number_to_currency(order.total_price - @shipping_price)
  -unless current_page?(new_order_path) || current_page?(orders_path)
    .order-summary-line
      SHIPPING: 
      %span
        -if order.delivery_type
          =number_to_currency(@shipping_price)
        -else
          %em not specified 
    .order-summary-line.main
      ORDER TOTAL: 
      %span= number_to_currency(order.total_price)

app/views/orders/_order_summary.html.haml
.col-md-4
  %h2.margin-bot-add Order summary
  .summary-line
    ITEM TOTAL: 
    %span= number_to_currency(@current_order.total_price)
  .summary-line
    SHIPPING: 
    %span
      =@current_order.delivery_type ? number_to_currency(@current_order.delivery_type.price) : "not specified"
  .summary-line
    ORDER TOTAL:
    %span= number_to_currency(@current_order.total_price) 

app/views/orders/_orders_table.html.haml
%table{class: "table"}
  %thead
    %tr
      %td NUMBER
      %td COMPLETED AT
      %td TOTAL
      %td DETAILS
  %tbody
    -orders.each do |order|
      %tr
        %td
          =order.id
        %td
          =order.completed_date.strftime("%Y-%m-%d")
        %td
          =number_to_currency(order.total_price)
        %td
          =link_to "view", order

app/views/orders/checkout_address.html.haml
.container.checkout
  =render "checkout_nav" 
  .row
    =form_for @checkout_address_form, url: set_address_orders_path do |f|
      .col-md-12
        -if @checkout_address_form.errors.any?
          %div.alert.alert-danger
            - @checkout_address_form.errors.full_messages.each do |msg|
              %div= "- " + msg
      .col-md-4
        %h2.margin-bot-add Billing address
        .row
          .col-md-8
            .form-group
              = f.label :b_firstname, "First name", class: "control-label"
              = f.text_field :b_firstname, class: "form-control"
            .form-group
              = f.label :b_lastname, "Last name", class: "control-label"
              = f.text_field :b_lastname, class: "form-control"
            .form-group
              = f.label :b_address, "Sreet address", class: "control-label"
              = f.text_field :b_address, class: "form-control"
            .form-group
              = f.label :b_city, "City", class: "control-label"
              = f.text_field :b_city, class: "form-control"
            .form-group
              = f.label :b_country_id, "Country", class: "control-label"
              = f.collection_select :b_country_id, @countries.order('name ASC'), :id, :name, {}, {class: "form-control"}
            .form-group
              = f.label :b_zipcode, "Zip", class: "control-label"
              = f.text_field :b_zipcode, class: "form-control"
            .form-group
              = f.label :b_phone, "Phone", class: "control-label"
              = f.text_field :b_phone, class: "form-control"
      .col-md-4
        %h2 Shipping address
        .row
          .col-md-8
            .form-group
              = f.check_box :use_billing_as_shipping, class: "checkbox-use-bill-address"
              = f.label :use_billing_as_shipping, "Use billing address" 
            .ship-address-form-fields      
              .form-group
                = f.label :s_firstname, "First name", class: "control-label"
                = f.text_field :s_firstname, class: "form-control"
              .form-group
                = f.label :s_lastname, "Last name", class: "control-label"
                = f.text_field :s_lastname, class: "form-control"
              .form-group
                = f.label :s_address, "Sreet address", class: "control-label"
                = f.text_field :s_address, class: "form-control"
              .form-group
                = f.label :s_city, "City", class: "control-label"
                = f.text_field :s_city, class: "form-control"
              .form-group
                = f.label :s_country_id, "Country", class: "control-label"
                = f.collection_select :s_country_id, @countries.order('name ASC'), :id, :name, {}, {class: "form-control"}
              .form-group
                = f.label :s_zipcode, "Zip", class: "control-label"
                = f.text_field :s_zipcode, class: "form-control"
              .form-group
                = f.label :s_phone, "Phone", class: "control-label"
                = f.text_field :s_phone, class: "form-control"
      =render "order_summary"    
      .col-md-4.col-md-offset-8
        .form-group
          = submit_tag "Save and continue", class: "btn btn-success btn-lg"

app/views/orders/checkout_confirm.html.haml
.container.checkout
  =render "checkout_nav" 
  -if @current_order.billing_address && @current_order.delivery_type && @current_order.credit_card
    .row
      .col-md-12
        %h2 Confirm

    =render partial: "order_details", locals: {order: @current_order}
    .row
      .col-md-4.col-md-offset-8
        = link_to "Place order", checkout_complete_orders_path, class: "btn btn-success btn-lg"
  -else
    %h2 Please, complete all previous steps.  
      

app/views/orders/checkout_delivery.html.haml
.container.checkout
  =render "checkout_nav" 
  =form_tag set_delivery_orders_path, method: "put" do
    .row
      / .col-md-12
      /   -if @current_order.errors.any?
      /     %div.alert.alert-danger
      /       - @current_order.errors.full_messages.each do |msg|
      /         %div= "- " + msg
      .col-md-8
        %h2.margin-bot-add Delivery type
        .row
          .col-md-8
            -@delivery_types.each_with_index do |dt, i|
              .radio
                = radio_button_tag :delivery_type, dt.id, i==0 
                = "#{dt.title} + #{number_to_currency(dt.price)}"
      =render "order_summary"    
      .col-md-4.col-md-offset-8
        .form-group
          = submit_tag "Save and continue", class: "btn btn-success btn-lg"

app/views/orders/checkout_payment.html.haml
.container.checkout
  =render "orders/checkout_nav"
  =form_for @credit_card do |f| 
    .row
      .col-md-8
        %h2.margin-bot-add Credit card
        .row
          .col-md-6
            -if @credit_card.errors.any?
              %div.alert.alert-danger
                - @credit_card.errors.full_messages.each do |msg|
                  %div= "- " + msg
            .form-group
              = f.label :firstname, "First name", class: "control-label"
              = f.text_field :firstname, class: "form-control"
            .form-group
              = f.label :lastname, "Last name", class: "control-label"
              = f.text_field :lastname, class: "form-control"
            .form-group
              = f.label :number, "Card number", class: "control-label"
              = f.text_field :number, class: "form-control"
            .form-group
              = f.label :exp_year, "Experation date: ", class: "control-label"
              - @years_array = []
              - (0..15).each do |i|
                - @years_array << [Date.today.year + i, Date.today.year.to_s.split("").last(2).join("").to_i + i]
              - @months_array = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
              = f.select(:exp_year, @years_array, prompt: "year")
              = f.select(:exp_month, @months_array, prompt: "month")
            .form-group
              = f.label :cvv, "CVV-code", class: "control-label"
              = f.text_field :cvv, class: "form-control cvv-field"          
      =render "orders/order_summary"    
      .col-md-4.col-md-offset-8
        .form-group
          = submit_tag "Save and continue", class: "btn btn-success btn-lg"

app/views/orders/index.html.haml
.container.orders_page
  .row
    .col-md-12
      %h1 Orders

      -if @current_order
        %h2.underlined-h2 In progress
        .row.cart
          =render partial: "order_items_list", locals: {order: @current_order}
        =link_to "Go to cart", new_order_path, class: "btn btn-primary lnk-to-cart"
      
      -if current_customer
        -if current_customer.orders.completed.any?
          %h2.underlined-h2 Waiting for processing
          =render partial: "orders_table", locals: {orders: current_customer.orders.completed}

        -if current_customer.orders.in_delivery.any?
          %h2.underlined-h2 In delivery
          =render partial: "orders_table", locals: {orders: current_customer.orders.in_delivery} 

        -if current_customer.orders.delivered.any?
          %h2.underlined-h2 Delivered
          =render partial: "orders_table", locals: {orders: current_customer.orders.delivered}

        -if current_customer.orders.empty?
          %p 
            You have no orders. Go to 
            =link_to "shop", books_path
            , find book you wish and click "Order" button.

      

app/views/orders/new.html.haml
.container
  %h1 Cart
  .row.cart  
    -if @current_order
      =form_tag '/orders/:id', method: :put do
        =render partial: "order_items_list", locals: {order: @current_order}
        .col-md-6
          =link_to "Empty cart", @current_order, class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" }
          =link_to "Continue shopping", books_path, class: "btn btn-primary"
        .col-md-6.right-btns 
          =link_to "Checkout", checkout_address_orders_path, class: "btn btn-success pull-right checkout-btn"
          =submit_tag "Update", class: "btn btn-default pull-right"

    -else 
      .col-md-12 
        Cart is empty. Find book you wish in
        =link_to "shop", books_path
        and click "Order" button. 

app/views/orders/show.html.haml
.container
  .row
    .col-md-12
      -if current_customer
        =link_to orders_path do
          .span{class: 'glyphicon glyphicon-chevron-left'}
          all your orders
      %h1
        -if current_page?(checkout_complete_orders_path)
          ="Congrats! Your order ##{@order.id} was successfully placed."
          %br/
          %small We'll call you soon to confirm it. 
        -else
          Order #
          =@order.id
  =render partial: "order_details", locals: {order: @order}