config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :customers, controllers: { registrations: 'customers/registrations', 
                                        sessions: 'customers/sessions',
                                        passwords: 'customers/passwords', 
                                        omniauth_callbacks: "customers/omniauth_callbacks" }
  devise_scope :customer do
    get '/settings', to: 'customers#settings'
    put '/change_password', to: 'customers#change_password'
    put '/change_personal_info', to: 'customers#change_personal_info'
  end
  
  resources :orders, only: [:index, :show, :new, :update, :destroy] do
    put "/add_to_order", to: "orders#add_to_order", on: :collection 
    get '/checkout_address', to: 'orders#checkout_address', on: :collection 
    post '/set_address', to: 'orders#set_address', on: :collection 
    get '/checkout_delivery', to: 'orders#checkout_delivery', on: :collection 
    put '/set_delivery', to: 'orders#set_delivery', on: :collection 
    get '/checkout_payment', to: 'orders#checkout_payment', on: :collection 
    get '/checkout_confirm', to: 'orders#checkout_confirm', on: :collection 
    get '/checkout_complete', to: 'orders#checkout_complete', on: :collection 
  end 
  
  resources :order_items, only: [:destroy] 
  resources :credit_cards, only: [:create, :update] 
  resources :addresses, only: [:update, :create]  
  resources :books, only: [:show, :index] do 
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:show]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= Customer.new # guest user (not logged in)
      can :read, [Book, Category]
      if user.is_a?(Admin)
        can :manage, :all
        can :access, :rails_admin   # grant access to rails_admin
        can :dashboard              # grant access to the dashboard
      elsif user.id?
        can :manage, Address, id: [user.billing_address_id, user.shipping_address_id] 
        can :read, Order, customer_id: user.id
      end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :country

  validates_presence_of :address, :zipcode, :city, :phone, :country, :lastname, :firstname
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates_presence_of :firstname, :lastname

  def title 
    "#{self.firstname} #{self.lastname}"
  end 
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  has_many :ratings, dependent: :destroy#, -> { order 'created_at desc' }

  validates_presence_of :title, :price, :amount

  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
	
	validates :title, presence: true, uniqueness: true
end

app/models/country.rb
class Country < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  POSSIBLE_EXP_MONTHES = ["01","02","03","04","05","06","07","08","09","10","11","12"]
  POSSIBLE_EXP_YEARS = []
  (0..15).each do |i|
    POSSIBLE_EXP_YEARS << (Date.today.year.to_s.split("").last(2).join("").to_i + i).to_s
  end

  belongs_to :customer
  has_many :orders

  validates_presence_of :number, :cvv, :exp_month, :exp_year, :firstname, :lastname
  validates :number, length:  { is: 16 }
  validates :cvv, length:  { is: 3 }
  validates :exp_month, :exp_year, length:  { is: 2 }
  validates :number, :cvv, :exp_year, format: { with: /\A\d+$\z/ }
  #validates :exp_month, format: { with: /\A(0+[1-9]|1+[12])\z/ }
  #validates :exp_year, format: { with: /\A(1+[5-9]|[2-9]+[1-9])\z/ }

  validates :exp_month, inclusion: { in: POSSIBLE_EXP_MONTHES }
  validates :exp_year, inclusion: { in: POSSIBLE_EXP_YEARS }

  def title 
    self.firstname + " " + self.lastname + " " + self.number
  end 
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
         
  has_many :orders
  has_many :ratings, dependent: :destroy
  has_one :credit_card

  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"

  validates_presence_of :email, :encrypted_password, :firstname, :lastname
  #validates :email, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def create_new_order
    self.orders.create
  end

  def current_order
    self.orders.in_progress.last
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.first_name   
      user.lastname = auth.info.last_name
    end
  end

  def title 
    self.firstname + " " + self.lastname
  end 
end

app/models/delivery_type.rb
class DeliveryType < ActiveRecord::Base
	validates_presence_of :title, :price
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  
  POSSIBLE_STATES = ['in_progress', 'completed', 'in_delivery', 'delivered', 'canceled']
  aasm column: "state" do
    state POSSIBLE_STATES[0].to_sym, initial: true
    state POSSIBLE_STATES[1].to_sym, after_enter: :set_completed_date
    state POSSIBLE_STATES[2].to_sym
    state POSSIBLE_STATES[3].to_sym
    state POSSIBLE_STATES[4].to_sym

    event :complete do
      transitions from: POSSIBLE_STATES[0].to_sym, to: POSSIBLE_STATES[1].to_sym
    end
  end

  default_scope { order('id DESC') } 

  belongs_to :customer
  belongs_to :credit_card
  belongs_to :delivery_type
  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"
  
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items

  validates_presence_of :completed_date, if: -> {self.state == POSSIBLE_STATES[1]}
  validates :state, inclusion: { in: POSSIBLE_STATES }, presence: true

  def add_to_order(book, quantity=1)  
    if order_item = self.order_items.find_by(book: book)
      order_item.quantity += quantity.to_i
      order_item.save
    else 
      self.order_items.create(price: book.price, quantity: quantity, book: book)
    end
    self.calc_and_set_total_price
  end

  def remove_from_order(item_id)
    OrderItem.find(item_id).destroy if self.order_items.ids.include?(item_id.to_i)
    self.destroy if self.order_items.empty?
  end

  def calc_and_set_total_price
    if self.order_items.any?
      item_total = self.order_items.inject(0) {|sum, i| sum + i.price*i.quantity} 
      shipping_price = self.delivery_type ? self.delivery_type.price : 0 
      self.total_price = item_total + shipping_price
    else 
      self.total_price = 0
    end
    self.save
  end

  def items_qty
    self.order_items.inject(0) {|sum, i| sum + i.quantity} if self.order_items.any?
  end

  def state_enum
    POSSIBLE_STATES
  end

  def set_completed_date
    self.update(completed_date: Date.today)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book

  validates_presence_of :price, :quantity, :book, :order
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :book
  belongs_to :customer

  validates_presence_of :rating_number, :review, :book, :customer

  scope :approved, -> {where(approved: true)}
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Amazon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 

  %body
    %nav.navbar.navbar-default
      .container.header
        .navbar-brand= link_to "BookStore", root_path
        %ul.nav.navbar-nav
          %li= link_to "Home", root_path, class: cp(root_path)
          %li= link_to "Shop", books_path, class: cp(books_path)
          %li{class: "cart-lnk"}
            = link_to new_order_path, class: cp(new_order_path) do 
              %span{class: "glyphicon glyphicon-shopping-cart"}
              CART:
              -if @current_order
                = @current_order.items_qty
                = @current_order.items_qty > 1 ? "books -" : "book -" 
                = number_to_currency(@current_order.total_price)
              -else 
                %em (empty)
          
        %ul.nav.navbar-nav.navbar-right  
          -if current_customer   
            %li= link_to "Settings", settings_path, class: cp(settings_path)        
            %li= link_to "Orders", orders_path, class: cp(orders_path)        
            %li= link_to "Sign out", destroy_customer_session_path, method: :delete
          -elsif current_admin  
            %li= link_to "Admin panel", rails_admin_path         
            %li= link_to "Log out", destroy_admin_session_path, method: :delete  
          -else 
            %li= link_to "Log in", new_customer_session_path, class: cp(new_customer_session_path)
            %li= link_to "Sign up", new_customer_registration_path, class: cp(new_customer_registration_path)
            
    .container.notifications
      / = @current_order.inspect
      / %br
      / = "current_order in sessin #{session[:current_order_id]}"
      - flash.each do |type, message|
        %div{:class => "alert #{bootstrap_class_for(type)}  alert-dismissible"}
          %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          = message

    = yield

    %br
    %br
  

app/views/pages/home.html.haml
.container
  %h1.text-center
    Welcome to our amazing Bookstore! 
    %br
    %small Choose anything you wish, we'll ship it anywhere.
  
  .row
    .col-md-10.col-md-offset-1
      .owl-carousel.home-page-slider
        -@books.each do |book|
          %div
            .col_md-4
              =link_to book do 
                =image_tag book.image.url.to_s, class: "thumbnail"
            .col-md-6
              %h2
                =link_to book do 
                  = book.title
                %br
                %small= "by #{book.author.firstname} #{book.author.lastname}" 
              %p= book.short_description
              %br
              .price= number_to_currency(book.price)
              .order-form-wrap
                =form_tag("/orders/add_to_order", method: "put") do
                  =number_field_tag 'quantity', "1", within: 1...10, class: 'quantity-input'
                  =hidden_field_tag 'book_id', book.id
                  =submit_tag "ADD TO CART", class: 'btn btn-primary' 